/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan;

import java.awt.Font;

/**
 *
 * @author VAIO
 */
public class MainFont extends javax.swing.JFrame {

    /**
     * Creates new form MainFont
     */
    public MainFont() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void getStyle(){
        Font font = null;
        
        if(cb_Bold.isSelected() && cb_Italic.isSelected() && cb_Perbesar.isSelected())
            font = new Font("Serif", Font.BOLD + Font.ITALIC,25);
        else if(cb_Bold.isSelected() && cb_Italic.isSelected() )
            font = new Font("Serif", Font.BOLD + Font.ITALIC,14);
        else if(cb_Perbesar.isSelected() && cb_Italic.isSelected() )
            font = new Font("Serif", Font.PLAIN + Font.ITALIC,25);
        else if(cb_Bold.isSelected() && cb_Perbesar.isSelected() )
            font = new Font("Serif", Font.BOLD + Font.PLAIN,25);
        else if(cb_Bold.isSelected())
            font = new Font("Serif", Font.BOLD, 14);
        else if(cb_Italic.isSelected())
            font = new Font("Serif", Font.ITALIC, 14);
         else if(cb_Perbesar.isSelected())
            font = new Font("Serif", Font.PLAIN ,25);
        else
            font = new Font("Serif", Font.PLAIN,14);
        lblHuruf.setFont(font);
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHuruf = new javax.swing.JLabel();
        cb_Bold = new javax.swing.JCheckBox();
        cb_Italic = new javax.swing.JCheckBox();
        cb_Perbesar = new javax.swing.JCheckBox();
        lblPerintah = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHuruf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHuruf.setText("Huruf Ini Akan Di Rubah");

        cb_Bold.setText("Bold");
        cb_Bold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_BoldActionPerformed(evt);
            }
        });

        cb_Italic.setText("Italic");
        cb_Italic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ItalicActionPerformed(evt);
            }
        });

        cb_Perbesar.setText("Perbesar");
        cb_Perbesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_PerbesarActionPerformed(evt);
            }
        });

        lblPerintah.setText("Perintah");

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPerintah, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_Italic)
                            .addComponent(cb_Bold)
                            .addComponent(cb_Perbesar))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblHuruf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Bold)
                    .addComponent(lblPerintah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_Italic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_Perbesar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_ItalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ItalicActionPerformed
        // TODO add your handling code here:
        getStyle(); 
    }//GEN-LAST:event_cb_ItalicActionPerformed

    private void cb_BoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_BoldActionPerformed
        // TODO add your handling code here:
        getStyle(); 
    }//GEN-LAST:event_cb_BoldActionPerformed

    private void cb_PerbesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_PerbesarActionPerformed
        // TODO add your handling code here:
        getStyle(); 
    }//GEN-LAST:event_cb_PerbesarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFont().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb_Bold;
    private javax.swing.JCheckBox cb_Italic;
    private javax.swing.JCheckBox cb_Perbesar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblHuruf;
    private javax.swing.JLabel lblPerintah;
    // End of variables declaration//GEN-END:variables
}
